name 'puppet-opal'
version '0.1.0'

author ''
license ''
project_page ''
source ''
summary ''
description ''
dependency 'puppetlabs/apt', '>=1.7.0'
dependency 'puppetlabs/java', '>=1.2.0'
dependency 'puppetlabs/mongodb', '>=0.8.0'
dependency 'puppetlabs/mysql', '>=2.3.1'
dependency 'puppetlabs/stdlib', '>=4.3.0'
dependency 'example42/puppi', '>=2.1.10'
